name: bike_store_admin_flutter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BSD
  # Android, IOS, Linux, macOS, WEB, Windows
  http: ^0.13.1
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3

  # MIT
  # Android, IOS, Linux, macOS, WEB, Windows
  provider: ^5.0.0
  equatable: ^2.0.0
  responsive_builder: ^0.4.1
  universal_html: ^2.0.8
  url_strategy: ^0.2.0

  # Apache 2.0
  # Android, IOS, Linux, macOS, WEB, Windows
  hive: ^2.0.3
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  test_core:

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
